#!/bin/bash
set -e

# Formats any *.tf files according to the hashicorp convention
files=$(git diff --diff-filter=d --cached --name-only)
for f in $files
do
  if [ -e "$f" ] && [[ "$f" == *.tf || "$f" == *.tfvars ]]; then
    which terraform > /dev/null 2&>1 && terraform fmt $f
    git add $f
  fi
done
